service: github-webhook

plugins:
  - serverless-step-functions
  - serverless-parameters
  - serverless-pseudo-parameters
  - serverless-make-portable-template

custom:
  parameters:
    GithubUsername:
      Type: String
      Default: ${env:GITHUB_USERNAME}
      Description: Github username, this is the user which will be displayed
    GithubAccessToken:
      Type: String
      Default: ${env:GITHUB_ACCESS_TOKEN}
      Description: Your generated github access token
      NoEcho: true
    CodebuildProject:
      Type: String
      Default: ${env:BUILD_PROJECT}
      Description: Name of the build project that should be triggered

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1

  # you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - codebuild:*
      Resource: '*'

  environment:
    BUILD_PROJECT:
      Ref: CodebuildProject
    GITHUB_USERNAME:
      Ref: GithubUsername
    GITHUB_ACCESS_TOKEN:
      Ref: GithubAccessToken

functions:
  start-build:
    handler: handler.start_build

  check-build-status:
    handler: handler.check_build_status

  build-done:
    handler: handler.build_done

resources:
  Outputs:
    TriggerEndpoint:
      Value:
        Fn::Join:
          - ""
          -
            - https://
            - Ref: "ApiGatewayRestApi"
            - .execute-api.eu-west-1.amazonaws.com/dev/trigger-build/

stepFunctions:
  stateMachines:
    build-for-commit:
      events:
        - http:
            path: trigger-build
            method: POST
      definition:
        Comment: "Check for build status for the given build project, and mark it when done on GH"
        StartAt: start_build
        States:
          start_build:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-start-build-#{AWS::StackName}"
            Next: check_build_status
          wait_a_bit:
            Type: Wait
            Seconds: 5
            Next: check_build_status
          check_build_status:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-check-build-status-#{AWS::StackName}"
            Next: check_build_status_outcome
          check_build_status_outcome:
            Type: Choice
            Choices:
            - Variable: "$.buildComplete"
              BooleanEquals: true
              Next: build_done
            Default: wait_a_bit
          build_done:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-build-done-#{AWS::StackName}"
            End: true
